In [15]:
# Import the modules
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


In [4]:
# Read the CSV file from the Resources folder into a Pandas DataFrame

csv_path = "Resources/data.csv"

# Import the data.csv file as a DataFrame
student_df = pd.read_csv(csv_path, encoding="utf-8",
                   sep = ';',
                   engine = 'python')

# Review the DataFrame
student_df.head()

Marital status  Application mode  Application order  Course   
0               1                17                  5     171  \
1               1                15                  1    9254   
2               1                 1                  5    9070   
3               1                17                  2    9773   
4               2                39                  1    8014   

   Daytime/evening attendance\t  Previous qualification   
0                             1                       1  \
1                             1                       1   
2                             1                       1   
3                             1                       1   
4                             0                       1   

   Previous qualification (grade)  Nacionality  Mother's qualification   
0                           122.0            1                      19  \
1                           160.0            1                       1   
2                           122.0            1                      37   
3                           122.0            1                      38   
4                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)   
0                      12  ...                                    0  \
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)   
0                                    0  \
1                                    6   
2                                    6   
3                                    6   
4                                    6   

   Curricular units 2nd sem (evaluations)   
0                                       0  \
1                                       6   
2                                       0   
3                                      10   
4                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)   
0                                    0                          0.000000  \
1                                    6                         13.666667   
2                                    0                          0.000000   
3                                    5                         12.400000   
4                                    6                         13.000000   

   Curricular units 2nd sem (without evaluations)  Unemployment rate   
0                                               0               10.8  \
1                                               0               13.9   
2                                               0               10.8   
3                                               0                9.4   
4                                               0               13.9   

   Inflation rate   GDP    Target  
0             1.4  1.74   Dropout  
1            -0.3  0.79  Graduate  
2             1.4  1.74   Dropout  
3            -0.8 -3.12  Graduate  
4            -0.3  0.79  Graduate  

[5 rows x 37 columns]

In [6]:
# Split the data into X (features) and y (target)
# The y variable should focus on the target column
y = student_df['Target']

# The X variable should include all features except the target
X = student_df.drop(columns=['Target'])

In [16]:
# Scale the feature data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [19]:
# Split into testing and training sets using train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2)

In [20]:
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(random_state=9, max_iter=1000, solver='saga')

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train, y_train)

In [21]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

In [22]:
# Create and save the confusion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)

# Print the confusion matrix for the training data
print(training_matrix)

[[ 886   95  157]
 [ 145  211  290]
 [  49   76 1630]]


In [23]:
# Create and save the confusion matrix for the testing data
test_matrix = confusion_matrix(y_test, testing_predictions)

# Print the confusion matrix for the testing data
print(test_matrix)

[[219  28  36]
 [ 44  44  60]
 [ 11  15 428]]


In [24]:
# Create and save the training classification report
training_report = classification_report(y_train, training_predictions)

# Print the training classification report
print(training_report)

              precision    recall  f1-score   support

     Dropout       0.82      0.78      0.80      1138
    Enrolled       0.55      0.33      0.41       646
    Graduate       0.78      0.93      0.85      1755

    accuracy                           0.77      3539
   macro avg       0.72      0.68      0.69      3539
weighted avg       0.75      0.77      0.75      3539

